paths:
  train_lr: /home/fc/Coding/CV/data/train/train_sharp_bicubic/X4
  train_hr: /home/fc/Coding/CV/data/train/train_sharp

  val_lr: /home/fc/Coding/CV/data/val/val_sharp_bicubic/X4
  val_hr: /home/fc/Coding/CV/data/val/val_sharp

  pretrain: /home/fc/Coding/CV/part2_2/models/RealESRGAN_x4plus.pth
  save_dir: /home/fc/Coding/CV/part2_2/experiments/realesrgan_x4plus_l1_finetune

train:
  scale: 4
  patch_size: 64
  batch_size: 4
  num_workers: 4

  epochs: 20
  lr: 1e-4
  weight_decay: 0.0

  loss_type: l1
  loss_weight: 1.0

  save_freq: 1
  val_freq: 1

  device: cuda
  seed: 42

resume:
  path: ""