paths:
  gt_dir: /home/fc/Coding/CV/data/val/val_sharp/000
  output_dir: /home/fc/Coding/CV/part3/results/metrics_adaptive_hybrid_val000_report

methods:
  BasicVSR++:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_val000_report/basic_frames
    suffix: ""

  Official-Real-ESRGAN:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_val000_report/generative_frames
    suffix: ""

  Direction-C-Hybrid:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_val000_report/frames
    suffix: ""

metrics:
  crop_border: 0
