paths:
  gt_dir: /home/fc/Coding/CV/data/val/val_sharp/000
  output_dir: /home/fc/Coding/CV/part3/results/metrics_000

methods:
  BasicVSR++:
    dir: /home/fc/Coding/CV/part3/results/hybrid_000/basic_frames
    suffix: ""

  ControlNet-Tile:
    dir: /home/fc/Coding/CV/part3/results/controlnet_tile_000
    suffix: ""

  Hybrid:
    dir: /home/fc/Coding/CV/part3/results/hybrid_000/frames
    suffix: ""

metrics:
  crop_border: 0

