paths:
  gt_dir: /home/fc/Coding/CV/data/val/val_sharp/000
  output_dir: /home/fc/Coding/CV/part3/results/metrics_adaptive_hybrid_000_conservative

methods:
  BasicVSR++:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_000_conservative/basic_frames
    suffix: ""

  Real-ESRGAN:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_000_conservative/generative_frames
    suffix: ""

  Adaptive-Hybrid-Conservative:
    dir: /home/fc/Coding/CV/part3/results/adaptive_hybrid_000_conservative/frames
    suffix: ""

metrics:
  crop_border: 0
